### ISSUE TITLE
ValueError: Please check symbol NIFTY  50

### ISSUE THREAD

**Issue by harshkumarchourasia** [NSEDownload/NSEDownload#21]
Error Message 
```
Traceback (most recent call last):
  File "/Users/harshkumarchourasia/Desktop/tangential/slots.py", line 4, in <module>
    df = indices.get_data(index_name="NIFTY  50", start_date="09-01-2017", end_date="14-08-2019")
  File "/Users/harshkumarchourasia/Desktop/tangential/venv/lib/python3.10/site-packages/NSEDownload/indices.py", line 63, in get_data
    index_name = check_name(index_name)
  File "/Users/harshkumarchourasia/Desktop/tangential/venv/lib/python3.10/site-packages/NSEDownload/indices.py", line 116, in check_name
    raise ValueError("Please check symbol " + name)
ValueError: Please check symbol NIFTY  50

Process finished with exit code 1
```
For the code
```
from NSEDownload import indices

# Getting historical data for index using date range
df = indices.get_data(index_name="NIFTY  50", start_date="09-01-2017", end_date="14-08-2019")

# Getting TRI data for index using date range
df = indices.get_data(index_name="NIFTY  50", start_date="09-01-2017", end_date="14-08-2019", indextype='TRI')
```

**Comment by jinit24** [comment]
Hi @harshkumarchourasia,
The extra space between NIFTY and 50 is causing a problem. Replace it with:
```python
df = indices.get_data(index_name="NIFTY 50", start_date="09-01-2017", end_date="14-08-2019")
```
I shall make the changes in readme as well. Thanks for pointing it out :)
