### ISSUE TITLE
Data for index NIFTY200 MOMENTUM30

### ISSUE THREAD

**Issue by elektor123** [NSEDownload/NSEDownload#9]
Hi,

I am not able to get data for  Nifty 200 Momnentum 30 index. I am seeing foloowing messages:

>>> df = indices.get_data(indexName = "NIFTY200 MOMENTUM 30",start_date="09-01-2017",end_date="14-08-2019")  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python391\lib\site-packages\NSEDownload\indices.py", line 69, in get_data
    check_name(Array, Values, indexName)
  File "C:\Python\Python391\lib\site-packages\NSEDownload\check.py", line 34, in check_name
    raise ValueError(
ValueError: Please check symbol provided. Try NIFTY200 Quality 30 as name.

Do I need to provide any other  name here.

**Comment by jinit24** [comment]
Hi elektor123,
The indexName that you used is cross-checked with an array in static_data.py
```python3
values = ["NIFTY 50", "NIFTY Next 50", "NIFTY Midcap Liquid 15", "NIFTY 100", "NIFTY 200", "NIFTY 500", "NIFTY Midcap 150", "NIFTY Midcap 50", "NIFTY Full Midcap 100", "NIFTY Midcap 100", "NIFTY Smallcap 250", "NIFTY Smallcap 50", "NIFTY Full Smallcap 100", "NIFTY Smallcap 100", "NIFTY LargeMidcap 250", "NIFTY MidSmallcap 400", "NIFTY Auto", "NIFTY Bank", "NIFTY Financial Services", "NIFTY FMCG", "NIFTY IT", "NIFTY Media", "NIFTY Metal", "NIFTY Pharma", "NIFTY Private Bank", "NIFTY PSU Bank", "NIFTY Realty", "NIFTY Commodities", "NIFTY India Consumption", "NIFTY CPSE", "NIFTY Energy", "NIFTY100 ESG", "NIFTY100 Enhanced ESG", "NIFTY Infra", "NIFTY MNC", "NIFTY PSE", "NIFTY SME EMERGE", "NIFTY Services Sector", "NIFTY Shariah 25", "NIFTY50 Shariah", "NIFTY500 Shariah", "NIFTY Aditya Birla Group", "NIFTY Mahindra Group", "NIFTY Tata Group", "NIFTY Tata Group 25% Cap", "NIFTY100 LIQ 15", "NIFTY Midcap Liquid 15", "NIFTY500 Value 50", "NIFTY Alpha Low-Volatility 30", "NIFTY Quality Low-Volatility 30", "NIFTY Alpha Quality Low-Volatility 30", "NIFTY Alpha Quality Value Low-Volatility 30", "NIFTY50 Equal Weight", "NIFTY100 Equal Weight", "NIFTY100 Low Volatility 30", "NIFTY50 USD", "NIFTY50 Dividend Points", "NIFTY Dividend Opportunities 50", "NIFTY100 Alpha 30", "NIFTY Alpha 50", "NIFTY 50 Arbitrage", "NIFTY 50 Futures Index", "NIFTY 50 Futures TR Index", "NIFTY High Beta 50", "NIFTY Low Volatility 50", "NIFTY200 Quality 30", "NIFTY100 Quality 30", "NIFTY50 Value 20", "NIFTY Growth Sectors 15", "NIFTY50 TR 2X Leverage", "NIFTY50 PR 2X Leverage", "NIFTY50 TR 1X Inverse", "NIFTY50 PR 1X Inverse", "NIFTY Composite G-sec Index", "NIFTY 4-8 yr G-Sec Index", "NIFTY 8-13 yr G-Sec", "NIFTY 10 yr Benchmark G-Sec", "NIFTY 10 yr Benchmark G-Sec (Clean Price)", "NIFTY 11-15 yr G-Sec Index", "NIFTY 15 yr and above G-Sec Index", "NIFTY 10 Year SDL Index", "NIFTY AAA Corporate Bond", "NIFTY AAA Ultra Short-Term Corporate Bond", "NIFTY AAA Short-Term Corporate Bond", "NIFTY AAA Medium-Term Corporate Bond", "NIFTY AAA Long-Term Corporate Bond", "NIFTY AAA Ultra Long-Term Corporate Bond", "Nifty 1D Rate Index"]
arr = ['NIFTY 50', 'NIFTY NEXT 50', 'NIFTY MID LIQ 15', 'NIFTY 100', 'NIFTY 200', 'NIFTY 500', 'NIFTY MIDCAP 150', 'NIFTY MIDCAP 50', 'NIFTY FULL MIDCAP 100', 'NIFTY MIDCAP 100', 'NIFTY SMALLCAP 250', 'NIFTY SMALLCAP 50', 'NIFTY FULL SMALLCAP 100', 'NIFTY SMLCAP 100', 'NIFTY LargeMidcap 250', 'NIFTY MIDSMALLCAP 400', 'NIFTY AUTO', 'NIFTY BANK', 'NIFTY FIN SERVICE', 'NIFTY FMCG', 'NIFTY IT', 'NIFTY MEDIA', 'NIFTY METAL', 'NIFTY PHARMA', 'NIFTY PVT BANK', 'NIFTY PSU BANK', 'NIFTY REALTY', 'NIFTY COMMODITIES', 'NIFTY CONSUMPTION', 'NIFTY CPSE', 'NIFTY ENERGY', 'NIFTY100 ESG', 'NIFTY100 Enhanced ESG', 'NIFTY INFRA', 'NIFTY MNC', 'NIFTY PSE', 'NIFTY SME EMERGE', 'NIFTY SERV SECTOR', 'NIFTY SHARIAH 25', 'NIFTY50 SHARIAH', 'NIFTY500 SHARIAH', 'NIFTY ADITYA BIRLA GROUP', 'NIFTY MAHINDRA GROUP', 'NIFTY TATA GROUP', 'NIFTY TATA GROUP 25% CAP', 'NIFTY100 LIQ 15', 'NIFTY MID LIQ 15', 'NIFTY500 VALUE 50', 'NIFTY ALPHA LOW-VOLATILITY 30', 'NIFTY QUALITY LOW-VOLATILITY 30', 'NIFTY ALPHA QUALITY LOW-VOLATILITY 30', 'NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30', 'NIFTY50 EQL WGT', 'NIFTY100 EQL WGT', 'NIFTY100 LOWVOL30', 'NIFTY50 USD', 'NIFTY50 DIV POINT', 'NIFTY DIV OPPS 50', 'NIFTY100 ALPHA 30', 'NIFTY ALPHA 50', 'NIFTY 50 ARBITRAGE', 'NIFTY 50 FUTURES INDEX', 'NIFTY 50 FUTURES TR INDEX', 'NIFTY HIGH BETA 50', 'NIFTY LOW VOLATILITY 50', 'NIFTY200 QUALITY 30', 'NIFTY100 Quality 30', 'NIFTY50 VALUE 20', 'NIFTY GROWSECT 15', 'NIFTY50 TR 2X LEV', 'NIFTY50 PR 2X LEV', 'NIFTY50 TR 1X INV', 'NIFTY50 PR 1X INV', 'NIFTY GS COMPSITE', 'NIFTY GS 4 8YR', 'NIFTY GS 8 13YR', 'NIFTY GS 10YR', 'NIFTY GS 10YR CLN', 'NIFTY GS 11 15YR', 'NIFTY GS 15YRPLUS', 'NIFTY 10 YEAR SDL INDEX', 'NIFTY AAA CORPORATE BOND', 'NIFTY AAA ULTRA SHORT-TERM CORPORATE BOND', 'NIFTY AAA SHORT-TERM CORPORATE BOND', 'NIFTY AAA MEDIUM-TERM CORPORATE BOND', 'NIFTY AAA LONG-TERM CORPORATE BOND', 'NIFTY AAA ULTRA LONG-TERM CORPORATE BOND', 'Nifty 1D Rate Index']
```
So, if the index name doesn't exist in it, the closest possible alternative is returned. Hence, NIFTY200 Quality 30 is returned. The issue with this list is that it isn't exhaustive and I would have to keep updating it for new indices.

Instead, if you are sure that you're index name is correct, you can bypass the check. 
1. Use **check_index=False**. 
2. Make sure the name is in upper case and properly spaced.
```python3
from NSEDownload import indices
df = indices.get_data(indexName = "NIFTY200 MOMENTUM 30", full_data=True, check_index=False)
```
Output:
```
| Date                | Open   | High   | Low   |    Close | Shares Traded   | Turnover (Rs. Cr)   |     |
|:--------------------|:-------|:-------|:------|---------:|:----------------|:--------------------|:----|
| 2005-04-01 00:00:00 | -      | -      | -     |  1000    | -               | -                   |     |
| 2005-04-04 00:00:00 | -      | -      | -     |  1000.01 | -               | -                   |     |
| 2005-04-05 00:00:00 | -      | -      | -     |   989.36 | -               | -                   |     |
| 2005-04-06 00:00:00 | -      | -      | -     |   994.63 | -               | -                   |     |
| 2005-04-07 00:00:00 | -      | -      | -     |   992.35 | -               | -                   |     |
| 2005-04-08 00:00:00 | -      | -      | -     |   979.83 | -               | -                   |     |
| 2005-04-11 00:00:00 | -      | -      | -     |   970.73 | -               | -                   |     |
| 2005-04-12 00:00:00 | -      | -      | -     |   981.29 | -               | -                   |     |
| 2005-04-13 00:00:00 | -      | -      | -     |   983.74 | -               | -                   |     |
| 2005-04-15 00:00:00 | -      | -      | -     |   951.85 | -               | -                   |     |
| 2005-04-18 00:00:00 | -      | -      | -     |   939.01 | -               | -                   |     |
| 2005-04-19 00:00:00 | -      | -      | -     |   932.5  | -               | -                   |     |
| 2005-04-20 00:00:00 | -      | -      | -     |   945.8  | -               | -                   |     |
| 2005-04-21 00:00:00 | -      | -      | -     |   959.38 | -               | -                   |     |
....
```
 I hope this solves your query.
